### ISSUE TITLE
Update README to include guidance on loading FontLibrary in spec file

### ISSUE THREAD

**Issue by josh-m-sharpe** [FortAwesome/angular-fontawesome#206]
I have successfully set up @fortawesome/angular-fontawesome@0.6.0-alpha.0 with angular 8 and loaded some icons.   The new alpha version looks solid 👏 👏 

That said, my specs are failing now with the error below.  This is presumably because my app loads the font library in AppModule, but my YsMainMenuComponent spec knows nothing about AppModule.

It would be very helpful if the readme here provided some guidance on injecting a FaFontLibrary into an angular spec correctly.

```
YsMainMenuComponent > should have link_to_home
Failed: Could not find icon with iconName=facebook and prefix=fab in the icon library.
error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 51101747, rootNodeFlags: 33554433, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 33554433, childFlags: 51101747, directChildFlags: 50380801, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 23, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: '', name: 'ion-content', attrs: [ Array ], template: null, componentProvider: Object({ nodeIndex: 1, parent: <circular reference: Object>, renderParent: <circular reference: Object>, bindingIndex: 0, outputIndex: 0, checkIndex: 1, flags: 49152, childFlags: 0, directChildFlags: 0, childMatchedQueries: 0, matchedQueries: Object, matchedQueryIds: 0, references: Object, ngContentIndex: -1, childCount: 0, bindings: Array, bindingFlags: 0, o ...
Error: Could not find icon with iconName=facebook and prefix=fab in the icon library.
    at faWarnIfIconDefinitionMissing (http://localhost:9876/_karma_webpack_/node_modules/@fortawesome/angular-fontawesome/fesm2015/angular-fontawesome.js:86:1)
    at FaIconComponent.findIconDefinition (http://localhost:9876/_karma_webpack_/node_modules/@fortawesome/angular-fontawesome/fesm2015/angular-fontawesome.js:226:1)
    at FaIconComponent.ngOnChanges (http://localhost:9876/_karma_webpack_/node_modules/@fortawesome/angular-fontawesome/fesm2015/angular-fontawesome.js:187:1)
    at checkAndUpdateDirectiveInline (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:31906:1)
    at checkAndUpdateNodeInline (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:44367:1)
    at checkAndUpdateNode (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:44306:1)
    at debugCheckAndUpdateNode (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:45328:36)
    at debugCheckDirectivesFn (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:45271:1)
    at Object.eval [as updateDirectives] (ng:///DynamicTestModule/YsMainMenuComponent.ngfactory.js:179:9)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:45259:1)
```

**Comment by josh-m-sharpe** [comment]
This SO seems like a very good approach: https://stackoverflow.com/a/58380192/115462

It might be worth considering updating the recommended installation/configuration steps of this library to follow that model.

**Comment by devoto13** [comment]
Thanks for the feedback @josh-m-sharpe.

Yes, your reasoning is correct. The latest version changed soft warnings about missing icons into the real errors to make sure they are easy to spot. And, yes, library is empty, because `AppModule` is not part of the spec.

You can find documentation on how to perform testing in the [documentation](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/guide/testing.md). Having said that I think that approach described in the linked SO answer should also be included in the angular-fontawesome documentation. Feel like submitting a PR?

**Comment by josh-m-sharpe** [comment]
Sure - can you point me to which documentation is best to update?

**Comment by devoto13** [comment]
It is the testing guide: https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/guide/testing.md

I would say put this approach as a first option in the *Test components using icon library* section as it is probably the one, which will work for the most of the library consumers.
