### ISSUE TITLE
Issue with prod build in Angular 8 w. v0.6

### ISSUE THREAD

**Issue by jrista** [FortAwesome/angular-fontawesome#208]
### Describe the problem

When performing a production build (`ng build --prod`), an error is encountered in the build optimizer.

### What did you expect?

A successful production build and deployable distribution.

### Reproducible test case

Working on a reproduction case...this is an Ionic 4 application, so StackBlitz is not an option.

Error message during prod build:

```
ERROR in ./node_modules/@fortawesome/angular-fontawesome/fesm2015/angular-fontawesome.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/Users/jonrista/contracts/wicshopper5/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/Users/jonrista/contracts/wicshopper5/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/Users/jonrista/contracts/wicshopper5/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/Users/jonrista/contracts/wicshopper5/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/Users/jonrista/contracts/wicshopper5/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/jonrista/contracts/wicshopper5/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/jonrista/contracts/wicshopper5/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/Users/jonrista/contracts/wicshopper5/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/jonrista/contracts/wicshopper5/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/jonrista/contracts/wicshopper5/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/Users/jonrista/contracts/wicshopper5/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/jonrista/contracts/wicshopper5/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/jonrista/contracts/wicshopper5/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/Users/jonrista/contracts/wicshopper5/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/jonrista/contracts/wicshopper5/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/jonrista/contracts/wicshopper5/node_modules/typescript/lib/typescript.js:16599:21)
```

**Comment by devoto13** [comment]
`angular-fontawesome` uses the standard way for packaging Angular libraries - `ng-packagr` and also fresh Angular CLI 8.x project builds without errors:

```
$ ng --version
...
Angular CLI: 8.3.2
$ ng new fa-test
$ cd fa-test
$ ng add @fortawesome/angular-fontawesome@0.6.0-alpha.0
$ ng build --prod
```

It may save you time to either try upgrading your Angular CLI tooling to latest 8.x release or use `angular-fontawesome@0.5.x` as older versions seem to fix this error for other libraries (https://github.com/angular/angular-cli/issues/15852). The problem is likely caused by the fact that you use older versions of tooling, but let's see if you manage to setup a reproduction repository I can look at.

**Comment by jrista** [comment]
I bumped up the CLI version to 8.3.2, then 8.3.8 (which was my npm global version), then finally the latest at 8.3.19 (locally and globally). Had the same issue each time. I then `ng update`d to NG 8.2 from 8.1, and still had the same problem. 

It looks like the issue may be coming from the angular-devkit, and some of the devkit versions are still 0.801.2, so I may try updating those as well. 

Before I downgrade to 0.5.x...what are the key differences between that and 0.6.x? Is it just the `ng add` schematic, or is there more than that? I originally chose 0.6 just because I wanted to benefit from `ng add` and have it do the bulk of the work for me. ;P

**Comment by jrista** [comment]
Ok...looks like I missed some CLI and builder related packages. I aligned the versions for all the following packages, and it seems to have worked:

```json
    "@angular-devkit/architect": "~0.803.19",
    "@angular-devkit/build-angular": "~0.803.19",
    "@angular-devkit/core": "~8.3.19",
    "@angular-devkit/schematics": "~8.3.19",
    "@angular/cli": "~8.3.19",
```

**Comment by jrista** [comment]
Ok, so, Ionic 4 is strictly dependent on all Angular 8.1.x packages, which I guess was the reason the local Angular CLI was 8.1.2. I reverted all the angular packages back to 8.1.2, and downgraded ng-fa to 0.5.0, and everything seems to be working, including the prod build. 

The Angular 8.2 and 8.3 builds produce a very different set of bundles than 8.1. I am not really sure what changed, but it does seem to be fairly significant...

**Comment by devoto13** [comment]
Sorry to hear! Hope it won’t take to much effort to fix the app.

If you decide to go with 0.5.x after all you can find the full list of changes in the [release notes](https://github.com/FortAwesome/angular-fontawesome/releases/tag/0.6.0-alpha.0). There are not so many new features besides Ivy support and ng-add.

**Comment by devoto13** [comment]
I see. Okay, than 0.5.x should be the way to go until Ionic supports newer versions of Angular CLI.

**Comment by jrista** [comment]
Yeah, it looks like 0.5.x works well with ng 8.1 and ionic 4. Nothing I've used out of it so far is having any problems, anyway. Prod build is working as well. I think there were just some major build system changes between 8.1 and 8.2 that seem to have broken things on a fairly broad scale (your package is far from the only one that has the same issue, it seems.)
