### ISSUE TITLE
Issue in Angular 9

### ISSUE THREAD

**Issue by koni-a** [FortAwesome/angular-fontawesome#243]
### we have updated the angular version 8 to 9

Package Version - "@fortawesome/angular-fontawesome": "^0.6.1", 

By Using Below link 

https://update.angular.io/#8.0:9.0l3

I am getting below error 

Error: Error on worker #1: Error: Failed to find exported name of node (CommonModule = (function () {
    function CommonModule() {
    }
    return CommonModule;
}())) in 'C:/TECH/PROJ/code/client/nb.cp.web/ClientApp/node_modules/angular-font-awesome/dist/angular-font-awesome.es5.js'.
    at Object.findExportedNameOfNode (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\imports\src\find_export.js:35:19)
    at LogicalProjectStrategy.emit (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\imports\src\emitter.js:228:38)
    at ReferenceEmitter.emit (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\imports\src\emitter.js:71:44)
    at Object.toR3Reference (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\util.js:173:31)
    at NgModuleDecoratorHandler._toR3Reference (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:415:31)
    at C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:196:72
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:196:38)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:341:40)
    at analyze (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:293:58)
    at ClusterMaster.onWorkerMessage (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:166:27)
    at C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:50:95
    at ClusterMaster.<anonymous> (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:246:57)
    at step (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\tslib\tslib.js:139:27)
    at Object.next (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\tslib\tslib.js:120:57)
    at C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\tslib\tslib.js:109:16)
    at EventEmitter.<anonymous> (C:\TECH\PROJ\code\client\nb.cp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:240:32)
    at EventEmitter.emit (events.js:321:20)
Compiling angular-font-awesome : module as esm5

Can you please help to resolve

**Comment by devoto13** [comment]
In your error message it says:

> Compiling angular-font-awesome : module as esm5

This error comes from the different package - [angular-font-awsome](https://github.com/baruchvlz/angular-font-awesome#readme), which is for FontAwesome 4. It looks like author of that library stopped maintaining it - repository is archived. Consider switching to FontAwesome 5 and `@fortawesome/angular-fontawesome` (this library), which works correctly with Angular 9. Check out [README](https://github.com/FortAwesome/angular-fontawesome#angular-fontawesome) to get started.

Closing as issue is with another library.
