### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by deveshsinghal22** [FortAwesome/angular-fontawesome#29]
I am getting below error, When I am trying to use icons in Angular v5.
It doesn't come instantly at the time of installation. but after some time it get triggered and need to revert all imports. 
```
ERROR in Error: Metadata version mismatch for module .. /node_modules/@fortawesome/angular-fontawesome/angular-fontawesome.d.ts, found version 4, expected 3, resolving symbol NavbarModule in ../src/app/shared/navbar/navbar.module.ts, resolving symbol NavbarModule in .. src/app/shared/navbar/navbar.module.ts
    at syntaxError (...\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (...\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (...\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at ...\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (...\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at ...\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (...\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (...\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (...\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (...\node_modules\@ngtools\webpack\src\plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (...\node_modules\@ngtools\webpack\src\plugin.js:448:24)
```

**Comment by devoto13** [comment]
@deveshsinghal22 this library works only with [Angular 5+](https://github.com/FortAwesome/angular-fontawesome/blob/c9cd5435a045e997fe5f112073de1d367dc63f01/package.json#L100).

**Comment by deveshsinghal22** [comment]
Ok, so it is an invalid.
