### ISSUE TITLE
Fix error to enable publishing using np

### ISSUE THREAD

**Issue by robmadole** [FortAwesome/angular-fontawesome#31]
This project includes integration with `np`. Which would be great to use.

The only issue is that when `npm run tagVersion` is ran the following occurs:

```
> @fortawesome/angular-fontawesome@0.1.0-8 tagVersion /Users/robmadole/Development/src/FortAwesome/angular-fontawesome
> node ./tasks/tag-version


Publish a new version of @fortawesome/angular-fontawesome (current: 0.1.0-8)

? Select semver increment or specify new version prerelease 	0.1.0-9
? How should this pre-release version be tagged in npm? prerelease

Commits:
- Revert "Adding np to dev deps"  8f632df
- Adding np to dev deps  05f7240
- Build fixes and fullTemplateTypeCheck support (#28)  f70ef0e

? Will bump from 0.1.0-8 to 0.1.0-9 and tag this release in npm as prerelease. Continue? Yes
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using Yarn
 ✔ Running tests
 ✔ Pushing tags

 @fortawesome/angular-fontawesome 0.1.0-8 published 🎉
Error: Command failed: npm test


    at Promise.all.then.arr (/Users/robmadole/Development/src/FortAwesome/angular-fontawesome/node_modules/np/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Command failed: npm test


    at Promise.all.then.arr (/Users/robmadole/Development/src/FortAwesome/angular-fontawesome/node_modules/np/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Command failed: npm test
module.js:538
    throw err;
    ^

Error: Cannot find module 'karma'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/robmadole/Development/src/FortAwesome/angular-fontawesome/tasks/test.js:5:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! Test failed.  See above for more details.


> @fortawesome/angular-fontawesome@0.1.0-8 test /Users/robmadole/Development/src/FortAwesome/angular-fontawesome
> node ./tasks/test


    at Promise.all.then.arr (/Users/robmadole/Development/src/FortAwesome/angular-fontawesome/node_modules/np/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Command failed: npm test
module.js:538
    throw err;
    ^

Error: Cannot find module 'karma'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/robmadole/Development/src/FortAwesome/angular-fontawesome/tasks/test.js:5:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! Test failed.  See above for more details.


> @fortawesome/angular-fontawesome@0.1.0-8 test /Users/robmadole/Development/src/FortAwesome/angular-fontawesome
> node ./tasks/test


    at Promise.all.then.arr (/Users/robmadole/Development/src/FortAwesome/angular-fontawesome/node_modules/np/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Execution of `np` errored, see above for more information.npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @fortawesome/angular-fontawesome@0.1.0-8 tagVersion: `node ./tasks/tag-version`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @fortawesome/angular-fontawesome@0.1.0-8 tagVersion script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robmadole/.npm/_logs/2018-04-10T15_00_07_202Z-debug.log
```

**Comment by devoto13** [comment]
Closing as obsolete.

While it may be useful to automate some publishing activities, this particular issue is not actionable.
