### ISSUE TITLE
fontawesome.module.d.ts is not exported from @fortawesome/angular-fontawesome

### ISSUE THREAD

**Issue by ArtemFrontendACTUM** [FortAwesome/angular-fontawesome#369]
### Describe the problem

```
Generated code for C:\Users\artem.kopchinskiy\Projects\Siko\js-storefront\spartacus\b2c\node_modules\@angular-devkit\build-angular\src\babel\webpack-loader.js??ruleSet[1].rules[2].use[0]!C:\Users\artem.kopchinskiy\Projects\Siko\js-storefront\spartacus\b2c\node_modules\@ngtools\webpack\src\ivy\index.js!C:\Users\artem.kopchinskiy\Projects\Siko\js-storefront\spartacus\b2c\node_modules\source-map-loader\dist\cjs.js??ruleSet[1].rules[3]!C:\Users\artem.kopchinskiy\Projects\Siko\js-storefront\spartacus\b2c\node_modules\css-loader\dist\runtime\cssWithMappingToString.js
1 | throw new Error("Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):\nError: Symbol FontAwesomeModule declared in C:/Users/artem.kopchinskiy/Projects/Siko/js-storefront/spartacus/libraries/node_modules/@fortawesome/angular-fontawesome/fontawesome.module.d.ts is not exported from @fortawesome/angular-fontawesome (import into C:/Users/artem.kopchinskiy/Projects/Siko/js-storefront/spartacus/libraries/projects/components/src/atomic/atomic-components.module.ts)\n    at AbsoluteModuleStrategy.emit (C:\\Users\\artem.kopchinskiy\\Projects\\Siko\\js-storefront\\spartacus\\b2c\\node_modules\\@angular\\compiler-cli\\src\\ngtsc\\imports\\src\\emitter.js:171:23)\n    at ReferenceEmitter.emit (C:\\Users\\artem.kopchinskiy\\Projects\\Siko\\js-storefront\\spartacus\\b2c\\node_modules\\@angular\\compiler-cli\\src\\ngtsc\\imports\\src\\emitter.js:72:44)\n    at Object.toR3Reference (C:\\Users\\artem.kopchinskiy\\Projects\\Siko\\js-storefront\\spartacus\\b2c\\node_modules\\@angular\\compiler-cli\\src\\ngtsc\\annotations\\src\\util.js:247:18)\n    at NgModuleDecoratorHandler._toR3Reference (C:\\Users\\artem.kopchinskiy\\Projects\\Siko\\js-storefront\\spartacus\\b2c\\node_modules\\@angular\\compiler-cli\\src\\ngtsc\\annotations\\src\\ng_module.js:527:31)\n    at C:\\Users\\artem.kopchinskiy\\Projects\\Siko\\js-storefront\\spartacus\\b2c\\node_modules\\@angular\\compiler-cli\\src\\ngtsc\\annotations\\src\\ng_module.js:266:72\n    at Array.map (<anonymous>)\n    at NgModuleDecoratorHandler.analyze (C:\\Users\\artem.kopchinskiy\\Projects\\Siko\\js-storefront\\spartacus\\b2c\\node_modules\\@angular\\compiler-cli\\src\\ngtsc\\annotations\\src\\ng_module.js:266:38)\n    at TraitCompiler.analyzeTrait (C:\\Users\\artem.kopchinskiy\\Projects\\Siko\\js-storefront\\spartacus\\b2c\\node_modules\\@angular\\compiler-cli\\src\\ngtsc\\transform\\src\\compilation.js:421:40)\n    at analyze (C:\\Users\\artem.kopchinskiy\\Projects\\Siko\\js-storefront\\spartacus\\b2c\\node_modules\\@angular\\compiler-cli\\src\\ngtsc\\transform\\src\\compilation.js:371:58)\n    at _loop_1 (C:\\Users\\artem.kopchinskiy\\Projects\\Siko\\js-storefront\\spartacus\\b2c\\node_modules\\@angular\\compiler-cli\\src\\ngtsc\\transform\\src\\compilation.js:393:21)");
```

## What happened? What are you seeing? How did you arrive here?

Working compilation

## How would you like this to work instead? 

Not working compilation

## Versions 
Node: v14.17.0
@fortawesome/angular-fontawesome": "^0.11.0",
"@fortawesome/fontawesome-free": "6.1.1",
"@fortawesome/fontawesome-svg-core": "^6.1.1",
"@fortawesome/free-regular-svg-icons": "^6.1.1",
"@fortawesome/free-solid-svg-icons": "^6.1.1",

**Comment by devoto13** [comment]
Hope you were able to resolve your problem by now.
If you still experience the problem and believe that there is a bug in `angular-fontawesome`, please provide a minimal reproduction we can look at.
