### ISSUE TITLE
Couldn't find package "@fortawesome/angular-fontawesome" on the "npm" registry.

### ISSUE THREAD

**Issue by hlohrenz** [FortAwesome/angular-fontawesome#68]
I am trying to add this package in a new project of mine and I get a 404. Sometimes, I will get a 404 as well.

This is the command I'm running:

`yarn add @fortawesome/angular-fontawesome`

Which is right on the homepage. Is anybody else experiencing this problem? I also had a previous project that had this and ran `yarn install`. This is my package.json file:

```
{
  "name": "frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@fortawesome/angular-fontawesome": "0.1.0-10",
    "@fortawesome/fontawesome-svg-core": "^1.2.0",
    "@fortawesome/free-brands-svg-icons": "^5.1.0",
    "@fortawesome/free-solid-svg-icons": "^5.1.0",
    "@fortawesome/pro-light-svg-icons": "^5.1.0",
    "@fortawesome/pro-regular-svg-icons": "^5.1.0",
    "@fortawesome/pro-solid-svg-icons": "^5.1.0",
    "@ng-bootstrap/ng-bootstrap": "^2.1.1",
    "bootstrap": "^4.1.1",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.6",
    "@angular/cli": "~6.0.7",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}
```

This is the error I get when I run `yarn install` instead:

`An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/angular-fontawesome/-/angular-fontawesome-0.1.0-10.tgz: Request failed \"401 Unauthorized\"".`

**Comment by lacroixdavid1** [comment]
Try to use `"@fortawesome/angular-fontawesome": "0.1.1"`

**Comment by robmadole** [comment]
@hlohrenz are you still experiencing this error?

**Comment by jlopezjuy** [comment]
i have the same error:
@fortawesome/angular-fontawesome": "0.1.1",
        "@fortawesome/fontawesome-svg-core": "1.2.2",
        "@fortawesome/free-solid-svg-icons": "5.2.0",

`npm WARN deprecated uws@9.14.0: stop using this version
npm ERR! code E401
npm ERR! 401 Unauthorized: @fortawesome/angular-fontawesome@0.1.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jlopez/.npm/_logs/2018-08-14T21_57_04_894Z-debug.log`

error log:
`9 silly saveTree └── zone.js@0.8.26
90 verbose stack Error: 401 Unauthorized: @fortawesome/angular-fontawesome@0.1.1
90 verbose stack     at fetch.then.res (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
90 verbose stack     at tryCatcher (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
90 verbose stack     at Promise._settlePromiseFromHandler (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
90 verbose stack     at Promise._settlePromise (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
90 verbose stack     at Promise._settlePromise0 (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
90 verbose stack     at Promise._settlePromises (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
90 verbose stack     at Async._drainQueue (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
90 verbose stack     at Async._drainQueues (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
90 verbose stack     at Immediate.Async.drainQueues (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
90 verbose stack     at runCallback (timers.js:810:20)
90 verbose stack     at tryOnImmediate (timers.js:768:5)
90 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
91 verbose cwd /media/jlopez/Disco D/Proyectos/España/V-Panel
92 verbose Linux 4.16.0-0.bpo.2-amd64
93 verbose argv "/usr/bin/node" "/home/jlopez/.npm-global/bin/npm" "install"
94 verbose node v8.11.3
95 verbose npm  v6.3.0
96 error code E401
97 error 401 Unauthorized: @fortawesome/angular-fontawesome@0.1.1
98 verbose exit [ 1, true ]
`

**Comment by devoto13** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/13794 describes potential issue and solution.
