### ISSUE TITLE
Error on npm install angular-fontawesome

### ISSUE THREAD

**Issue by jlopezjuy** [FortAwesome/angular-fontawesome#82]
Hello, i have an error when im trying to run npm install

`ERR! code E401
npm ERR! 401 Unauthorized: @fortawesome/fontawesome-svg-core@1.2.2
`
It's my package.json
```
{
  "name": "vpanel",
  "version": "0.0.0",
  "description": "Description for vpanel",
  "private": true,
  "license": "UNLICENSED",
  "cacheDirectories": [
    "node_modules"
  ],
  "dependencies": {
    "@angular/common": "6.1.0",
    "@angular/compiler": "6.1.0",
    "@angular/core": "6.1.0",
    "@angular/forms": "6.1.0",
    "@angular/platform-browser": "6.1.0",
    "@angular/platform-browser-dynamic": "6.1.0",
    "@angular/router": "6.1.0",
    "@fortawesome/angular-fontawesome": "0.1.1",
    "@fortawesome/fontawesome-svg-core": "1.2.2",
    "@fortawesome/free-solid-svg-icons": "5.2.0",
    "@ng-bootstrap/ng-bootstrap": "2.2.1",
    "bootstrap": "4.1.3",
    "core-js": "2.5.7",
    "jquery": "3.3.1",
    "moment": "2.22.2",
    "ng-jhipster": "0.5.4",
    "ngx-cookie": "2.0.1",
    "ngx-infinite-scroll": "0.5.1",
    "ngx-webstorage": "2.0.1",
    "reflect-metadata": "0.1.12",
    "rxjs": "6.1.0",
    "rxjs-compat": "6.1.0",
    "swagger-ui": "2.2.10",
    "sockjs-client": "1.1.4",
    "webstomp-client": "1.2.0",
    "tslib": "1.9.3",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "6.1.2",
    "@angular/compiler-cli": "6.1.0",
    "@ngtools/webpack": "6.0.0",
    "@types/jest": "22.2.3",
    "@types/node": "9.4.7",
    "angular-router-loader": "0.8.5",
    "angular2-template-loader": "0.6.2",
    "browser-sync": "2.24.4",
    "browser-sync-webpack-plugin": "2.2.2",
    "cache-loader": "1.2.2",
    "codelyzer": "4.2.1",
    "copy-webpack-plugin": "4.5.1",
    "css-loader": "0.28.10",
    "exports-loader": "0.7.0",
    "extract-text-webpack-plugin": "4.0.0-beta.0",
    "file-loader": "1.1.11",
    "fork-ts-checker-webpack-plugin": "0.4.1",
    "friendly-errors-webpack-plugin": "1.7.0",
    "generator-jhipster": "5.2.0",
    "html-loader": "0.5.5",
    "html-webpack-plugin": "3.2.0",
    "husky": "0.14.3",
    "jest": "22.4.3",
    "jest-junit": "5.1.0",
    "jest-preset-angular": "5.2.2",
    "jest-sonar-reporter": "2.0.0",
    "lint-staged": "7.0.0",
    "merge-jsons-webpack-plugin": "1.0.14",
    "moment-locales-webpack-plugin": "1.0.5",
    "prettier": "1.11.1",
    "proxy-middleware": "0.15.0",
    "raw-loader": "0.5.1",
    "rimraf": "2.6.1",
    "simple-progress-webpack-plugin": "1.1.2",
    "style-loader": "0.20.3",
    "tapable": "1.0.0",
    "terser-webpack-plugin": "1.0.0",
    "thread-loader": "1.1.5",
    "to-string-loader": "1.1.5",
    "ts-loader": "4.0.1",
    "tslint": "5.9.1",
    "tslint-config-prettier": "1.9.0",
    "tslint-loader": "3.6.0",
    "typescript": "2.7.2",
    "xml2js": "0.4.19",
    "generator-jhipster-docker": "2.5.0",
    "generator-jhipster-audit-helper": "1.0.3",
    "webpack": "4.8.0",
    "webpack-cli": "2.1.3",
    "webpack-dev-server": "3.1.4",
    "webpack-merge": "4.1.2",
    "webpack-notifier": "1.6.0",
    "webpack-visualizer-plugin": "0.1.11",
    "workbox-webpack-plugin": "3.2.0",
    "write-file-webpack-plugin": "4.2.0"
  },
  "engines": {
    "node": ">=8.9.0"
  },
  "lint-staged": {
    "src/**/*.{ts,css,scss}": ["prettier --write", "git add"]
  },
  "scripts": {
    "precommit": "lint-staged",
    "prettier:format": "npm prettier --write 'src/**/*.{ts,css,scss}'",
    "lint": "tslint --project tsconfig.json -e 'node_modules/**'",
    "lint:fix": "npm run lint -- --fix",
    "ngc": "ngc -p tsconfig-aot.json",
    "cleanup": "rimraf target/{aot,www}",
    "clean-www": "rimraf target//www/app/{src,target/}",
    "start": "npm run webpack:dev",
    "serve": "npm run start",
    "build": "npm run webpack:prod",
    "test": "npm run lint && jest --coverage --logHeapUsage -w=2 --config src/test/javascript/jest.conf.js",
    "test:watch": "npm test -- --watch --clearCache",
    "webpack:dev": "npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --hot --port=9060 --watch-content-base --env.stats=minimal",
    "webpack:dev-verbose": "npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --hot --port=9060 --watch-content-base --profile --progress --env.stats=normal",
    "webpack:build:main": "npm run webpack -- --config webpack/webpack.dev.js --env.stats=normal",
    "webpack:build": "npm run cleanup && npm run webpack:build:main",
    "webpack:prod:main": "npm run webpack -- --config webpack/webpack.prod.js --profile",
    "webpack:prod": "npm run cleanup && npm run webpack:prod:main && npm run clean-www",
    "webpack:test": "npm run test",
    "webpack-dev-server": "node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "webpack": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js"
  },
  "jestSonar": {
    "reportPath": "target/test-results/jest",
    "reportFile": "TESTS-results-sonar.xml"
  }
}
```

and the error log:

```
3364 silly saveTree └── zone.js@0.8.26
3365 verbose stack Error: 401 Unauthorized: @fortawesome/fontawesome-svg-core@1.2.2
3365 verbose stack     at fetch.then.res (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
3365 verbose stack     at tryCatcher (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
3365 verbose stack     at Promise._settlePromiseFromHandler (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
3365 verbose stack     at Promise._settlePromise (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
3365 verbose stack     at Promise._settlePromise0 (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
3365 verbose stack     at Promise._settlePromises (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
3365 verbose stack     at Async._drainQueue (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
3365 verbose stack     at Async._drainQueues (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
3365 verbose stack     at Immediate.Async.drainQueues (/home/jlopez/.npm-global/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
3365 verbose stack     at runCallback (timers.js:810:20)
3365 verbose stack     at tryOnImmediate (timers.js:768:5)
3365 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
3366 verbose cwd /media/jlopez/Disco D/Proyectos/España/V-Panel
3367 verbose Linux 4.16.0-0.bpo.2-amd64
3368 verbose argv "/usr/bin/node" "/home/jlopez/.npm-global/bin/npm" "install"
3369 verbose node v8.11.3
3370 verbose npm  v6.3.0
3371 error code E401
3372 error 401 Unauthorized: @fortawesome/fontawesome-svg-core@1.2.2
3373 verbose exit [ 1, true ]
```

I hope you helpme.

**Comment by paustint** [comment]
@jlopezjuy you will need to make sure that you setup your key for npm as mentioned here: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

Create a file named `.npmrc` and add the following to the contents:
```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=YOUR-KEY-GOES-HERE
```

From there you should not get 404's

**Comment by devoto13** [comment]
@jlopezjuy can you check https://github.com/FortAwesome/Font-Awesome/issues/13794 and try to follow [this instruction](https://github.com/FortAwesome/Font-Awesome/issues/13794#issuecomment-414399956)?

**Comment by devoto13** [comment]
Closing as no feedback and can not reproduce. Please follow the recommendation linked in the previous comment and if it still does not work open a new issue.
